import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import { Inter } from "next/font/google";
import Headers from "@/components/header";
import InforHeader from "@/components/home-component/infor-header";
import Link from "next/link";
import Footer from "@/components/footer";
import { Toaster } from "sonner";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";
import { se } from "date-fns/locale";
import HeaderLogin from "@/components/heade-login";
import ChatBotWidget from "@/components/chatbotai/chatbotcompoent";
import { headers } from "next/headers";
// import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["vietnamese"],
  variable: "--font-inter",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname();
  // const hideHeader = pathname === "/login" || pathname === "/register";

  const cookieStore: any = await cookies();
  const sessionToken = cookieStore.get("sessionToken");

  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <InforHeader />
          {sessionToken?.value ? <HeaderLogin /> : <Headers />}

          <AppProvider inittialValue={sessionToken?.value}>
            {children}
          </AppProvider>
          <ChatBotWidget />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
