import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import { Inter } from "next/font/google";
import Headers from "@/components/header";
import InforHeader from "@/components/home-component/infor-header";
import Link from "next/link";
import Footer from "@/components/footer";
// import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["vietnamese"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname();
  // const hideHeader = pathname === "/login" || pathname === "/register";
  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <InforHeader />
          <Headers />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
