import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["vietnamese"],
  variable: "--font-inter",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore: any = await cookies();
  const sessionToken = cookieStore.get("sessionToken");

  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <AppProvider inittialValue={sessionToken?.value}>
            {children}
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
